# Generated by Django 5.0.4 on 2024-06-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='unit',
            field=models.CharField(max_length=60),
        ),
    ]
